# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

_target_: blueprint.trainers.MomentMatchingTrainer
mmd_model:
  _target_: blueprint.losses.mmd.MMDRFF
  n_features: 256
  dist:
    _target_: blueprint.models.kernels.NormalDistribution
    n_kernels: 5
    n_subsample: 128